# Generated by Django 5.0.6 on 2025-12-11 17:47

from django.db import migrations


DATA = """
Arusha Region,Meru District Council
Arusha Region,Arusha City Council
Arusha Region,Arusha District Council
Arusha Region,Karatu District Council
Arusha Region,Longido District Council
Arusha Region,Monduli District Council
Arusha Region,Ngorongoro District Council
Dar es Salaam Region,Ilala Municipal Council
Dar es Salaam Region,Kinondoni Municipal Council
Dar es Salaam Region,Temeke Municipal Council
Dodoma Region,Bahi District Council
Dodoma Region,Chamwino District Council
Dodoma Region,Chemba District Council
Dodoma Region,Dodoma Municipal Council
Dodoma Region,Kondoa District Council
Dodoma Region,Kongwa District Council
Dodoma Region,Mpwapwa District Council
Geita Region,Bukombe District Council
Geita Region,Chato District Council
Geita Region,Geita Town Council & Geita District Council
Geita Region,Mbongwe District Council
Geita Region,Nyang'hwale District Council
Iringa Region,Iringa District Council
Iringa Region,Iringa Municipal Council
Iringa Region,Kilolo District Council
Iringa Region,Mafinga Town Council
Iringa Region,Mufindi District Council
Kagera Region,Biharamulo District Council
Kagera Region,Bukoba District Council
Kagera Region,Bukoba Municipal Council
Kagera Region,Karagwe District Council
Kagera Region,Kyerwa District Council
Kagera Region,Missenyi District Council
Kagera Region,Muleba District Council
Kagera Region,Ngara District Council
Kaskazini Pemba Region of Zanzibar,Micheweni District
Kaskazini Pemba Region of Zanzibar,Wete District
Kaskazini Unguja Region of Zanzibar,Kaskazini A District
Kaskazini Unguja Region of Zanzibar,Kaskazini B District
Katavi Region,Mlele District Council
Katavi Region,Mpanda District Council
Katavi Region,Mpanda Town Council
Kigoma Region,Buhigwe District Council
Kigoma Region,Kakonko District Council
Kigoma Region,Kasulu District Council
Kigoma Region,Kasulu Town Council
Kigoma Region,Kibondo District Council
Kigoma Region,Kigoma District Council
Kigoma Region,Kigoma-Ujiji Municipal Council
Kigoma Region,Uvinza District Council
Kilimanjaro Region,Hai District Council
Kilimanjaro Region,Moshi District Council
Kilimanjaro Region,Moshi Municipal Council
Kilimanjaro Region,Mwanga District Council
Kilimanjaro Region,Rombo District Council
Kilimanjaro Region,Same District Council
Kilimanjaro Region,Siha District Council
Kusini Pemba Region of Zanzibar,Chake Chake District
Kusini Pemba Region of Zanzibar,Mkoani District
Kusini Unguja Region of Zanzibar,Kati District
Kusini Unguja Region of Zanzibar,Kusini District
Lindi Region,Kilwa District Council
Lindi Region,Lindi District Council
Lindi Region,Lindi Municipal Council
Lindi Region,Liwale District Council
Lindi Region,Nachingwea District Council
Lindi Region,Ruangwa District Council
Manyara Region,Babati Town Council
Manyara Region,Babati District Council
Manyara Region,Hanang District Council
Manyara Region,Kiteto District Council
Manyara Region,Mbulu District Council
Manyara Region,Simanjiro District Council
Mara Region,Bunda District Council
Mara Region,Butiama District Council
Mara Region,Musoma District Council
Mara Region,Musoma Municipal Council
Mara Region,Rorya District Council
Mara Region,Serengeti District Council
Mara Region,Tarime District Council
Mbeya Region,Chunya District Council
Mbeya Region,Ileje District Council
Mbeya Region,Kyela District Council
Mbeya Region,Mbarali District Council
Mbeya Region,Mbeya City Council
Mbeya Region,Mbeya District Council
Mbeya Region,Mbozi District Council
Mbeya Region,Momba District Council
Mbeya Region,Rungwe District Council
Mbeya Region,Tunduma Town Council
Mjini Magharibi Region of Zanzibar,Magharibi District
Mjini Magharibi Region of Zanzibar,Mjini District
Morogoro Region,Gairo District Council
Morogoro Region,Kilombero District Council
Morogoro Region,Kilosa District Council
Morogoro Region,Morogoro District Council
Morogoro Region,Morogoro Municipal Council
Morogoro Region,Mvomero District Council
Morogoro Region,Ulanga District Council
Mtwara Region,Masasi District Council
Mtwara Region,Masasi Town Council
Mtwara Region,Mtwara District Council
Mtwara Region,Mtwara Municipal Council
Mtwara Region,Nanyumbu District Council
Mtwara Region,Newala District Council
Mtwara Region,Tandahimba District Council
Mwanza Region,Ilemela Municipal Council
Mwanza Region,Kwimba District Council
Mwanza Region,Magu District Council
Mwanza Region,Misungwi District Council
Mwanza Region,Nyamagana Municipal Council
Mwanza Region,Sengerema District Council
Mwanza Region,Ukerewe District Council
Njombe Region,Ludewa District Council
Njombe Region,Makambako Town Council
Njombe Region,Makete District Council
Njombe Region,Njombe District Council
Njombe Region,Njombe Town Council
Njombe Region,Wanging'ombe District Council
Pwani Region,Bagamoyo District Council
Pwani Region,Kibaha District Council
Pwani Region,Kibaha Town Council
Pwani Region,Kisarawe District Council
Pwani Region,Mafia District Council
Pwani Region,Mkuranga District Council
Pwani Region,Rufiji District Council
Rukwa Region,Kalambo District Council
Rukwa Region,Nkasi District Council
Rukwa Region,Sumbawanga District Council
Rukwa Region,Sumbawanga Municipal Council
Ruvuma Region,Mbinga District Council
Ruvuma Region,Songea District Council
Ruvuma Region,Songea Municipal Council
Ruvuma Region,Tunduru District Council
Ruvuma Region,Namtumbo District Council
Ruvuma Region,Nyasa District Council
Shinyanga Region,Kahama Town Council
Shinyanga Region,Kahama District Council
Shinyanga Region,Kishapu District Council
Shinyanga Region,Shinyanga District Council
Shinyanga Region,Shinyanga Municipal Council
Simiyu Region,Bariadi District Council
Simiyu Region,Busega District Council
Simiyu Region,Itilima District Council
Simiyu Region,Maswa District Council
Simiyu Region,Meatu District Council
Singida Region,Ikungi District Council
Singida Region,Iramba District Council
Singida Region,Manyoni District Council
Singida Region,Mkalama District Council
Singida Region,Singida District Council
Singida Region,Singida Municipal Council
Tabora Region,Igunga District Council
Tabora Region,Kaliua District Council
Tabora Region,Nzega District Council
Tabora Region,Sikonge District Council
Tabora Region,Tabora Municipal Council
Tabora Region,Urambo District Council
Tabora Region,Uyui District Council
Tanga Region,Handeni District Council
Tanga Region,Handeni Town Council
Tanga Region,Kilindi District Council
Tanga Region,Korogwe Town Council
Tanga Region,Korogwe District Council
Tanga Region,Lushoto District Council
Tanga Region,Muheza District Council
Tanga Region,Mkinga District Council
Tanga Region,Pangani District Council
Tanga Region,Tanga City Council
"""

def populate_data(apps, schema_editor):
    Region = apps.get_model('apply', 'Region')
    District = apps.get_model('apply', 'District')
    
    for line in DATA.strip().split('\n'):
        region_name, district_name = line.strip().split(',')
        region, created = Region.objects.get_or_create(name=region_name)
        District.objects.get_or_create(region=region, name=district_name)


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'), # Make sure this matches your previous migration file
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
