# Generated by Django 5.0.6 on 2025-12-11 19:37

from django.db import migrations

SESSIONS_TO_CREATE = [
    "Morning",
    "Afternoon",
    "Evening",
    "Night",
]

def populate_sessions(apps, schema_editor):
    Session = apps.get_model('apply', 'Session')
    for session_name in SESSIONS_TO_CREATE:
        Session.objects.get_or_create(name=session_name)

class Migration(migrations.Migration):
    dependencies = [
        ('apply', '0002_populate_regions_districts'),
    ]
    operations = [
        migrations.RunPython(populate_sessions),
    ]