# Generated by Django 6.0 on 2025-12-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_populate_regions_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='kitongoji',
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='courses', to='apply.session'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.session'),
        ),
        migrations.DeleteModel(
            name='Kitongoji',
        ),
    ]
