# Generated by Django 6.0 on 2025-12-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_remove_student_fullname_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='courses', to='apply.session'),
        ),
    ]
