# Generated by Django 6.0 on 2025-12-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_populate_sessions'),
        ('apply', '0004_populate_sessions'),
    ]

    operations = [
    ]
