# Generated by Django 6.0 on 2025-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_auto_20251212_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a picture for the course.', null=True, upload_to='course_images/'),
        ),
    ]
