# Generated by Django 6.0 on 2025-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_approved',
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved')], default='UNPAID', max_length=10),
        ),
    ]
