# Generated by Django 6.0 on 2026-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
